### PR TITLE
form-field: apply function in attrs mode. Fix #192

### LINKED ISSUE #192: Cannot read property 'name' of undefined

### PR DESCRIPTION
**Pull request by kompolom**

### CODE REVIEW

**Comment by awinogradov** [comment]
main branch is v1.0.0 ;)

**Comment by adinvadim** [comment]
and a bug has already been fixed 
https://github.com/bem-contrib/bem-forms/pull/188

**Comment by kompolom** [comment]
@awinogradov I know, but we use master branch in our project.

**Comment by awinogradov** [comment]
You can merge it on your level. We merge v1.0.0 branch into master and you'll get all new changes. You should be ready for this.

**Pull request closed without merging**
